### ISSUE TITLE
Can't work on Python3.6@Ubuntu 18.04

### ISSUE THREAD

**Issue by choloxyz** [miguelmalvarez/downloadTwitterPictures#3]
It doesn't work with Python3.6 >_< reporting KeyError 
Btw I have checked that I have installed all needed python libs
Here;s the log.

> root@CholoWorks_Official:~/downloadTwitterPictures/src# python3 run.py --username sexfri_end --num 10
> Traceback (most recent call last):
>   File "run.py", line 112, in <module>
>     main()
>   File "run.py", line 103, in main
>     auth = authorise_twitter_api(config)
>   File "run.py", line 43, in authorise_twitter_api
>     auth = OAuthHandler(config['DEFAULT']['[I have replaced it to my own key and secret , as well as the ones in the ../config.cfg]'], config['DEFAULT']['[I have replaced it to my own key and secret , as well as the ones in the ../config.cfg]'])
>   File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
>     raise KeyError(key)
> KeyError: '[I have replaced it to my own key and secret , as well as the ones in the ../config.cfg]'

**Comment by miguelmalvarez** [comment]
You don't have to modify the auth line in the code. It should stay as it is:

auth = OAuthHandler(config['DEFAULT']['consumer_key'], config['DEFAULT']['consumer_secret'])
auth.set_access_token(config['DEFAULT']['access_token'], config['DEFAULT']['access_secret'])

You only have to modify the config.cfg file to include your key and secret. Example (with fake keys):

[DEFAULT]
consumer_key = UTFJT3uPM4NBBcgFaJ9iS
consumer_secret = AczasA78Z9IsyEyxCaRuBit
access_token = 2RT78F9-AQL6lDvSs7Zrw87Fr5
access_secret = B2987sjrtJopS5IRKIOHgiFrTq9c98

**Comment by choloxyz** [comment]
Thanks and that works perfectly!
I'll go add some feature in several days ( in the form of pull request )
