### ISSUE TITLE
Getting some issue when I start to debug the code

### ISSUE THREAD

**Issue by ladycatusa** [miguelmalvarez/downloadTwitterPictures#7]
Hi miguelmalvarez,

I love this tutorial and I learn a lot, although I keep getting this error as below 👍 

tweepy .error.TweepError: Twitter error response: status code = 400

here is the error 

Traceback (most recent call last):
  File "run.py", line 136, in <module>
    main()
  File "run.py", line 133, in main
    download_images_by_user(api, username, retweets, replies, num_tweets, output_folder)
  File "run.py", line 110, in download_images_by_user
    download_images(status, num_tweets, output_folder)
  File "run.py", line 95, in download_images
    for tweet_status in status:

I think there is something in here, would you please suggest what might cause this?

I'm using python 3.7.3 and tweepy 3.8.

Thanks

**Comment by miguelmalvarez** [comment]
Hi, 

Thanks for the kind words. Can you share the specific command you are using to get this behaviour?

Regards,
